-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- 主机: 127.0.0.1
-- 生成日期: 2018-05-25 06:05:04
-- 服务器版本: 5.5.57-0ubuntu0.14.04.1
-- PHP 版本: 5.5.9-1ubuntu4.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- 数据库: `fruit`
--

-- --------------------------------------------------------

--
-- 表的结构 `products`
--

CREATE TABLE IF NOT EXISTS `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(24) NOT NULL,
  `description` text NOT NULL,
  `price` decimal(8,2) NOT NULL,
  `onspecial` tinyint(1) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=147 ;

--
-- 转存表中的数据 `products`
--

INSERT INTO `products` (`id`, `name`, `description`, `price`, `onspecial`, `active`, `created`, `modified`) VALUES
(65, 'Apple', 'Apples are the the most popular of all fruits and also generally available all year round. Perfect for eating raw as a snack and an ideal for making puddings and desserts.\n', '343.73', 0, 1, '2017-01-23 12:17:33', '2017-01-23 12:17:33'),
(66, 'Avocado', 'Avocados are the only fruit that contain fat (monounsaturated fat). They are best eaten raw, sliced, or added to salads', '176.74', 0, 1, '2017-01-23 12:19:00', '2017-01-23 12:19:00'),
(67, 'Bananas', 'Bananas are rich in potassium, riboflavin, niacin, and dietary fibre. They also have high energy value and are really good for growing children and athletes. They are also excellent for low-salt, low-fat, and cholesterol-free diets. Hundreds of different varieties of banana flourish in the tropics, from sweet yellow pygmy to large fibrous plantains and green bananas, which can only be used for cooking. ', '265.47', 0, 1, '2017-01-23 12:19:00', '2017-01-23 12:19:00'),
(68, 'Blackberry', 'The blackberry has always grown in the wild and is a widespread genus. It also seems to be a native to many parts of the world including Britain, North America, and Africa. Captain John Smith was introduced to the blackberries that were growing in the wilds of America. The blackberry is also a member of the rose family—not a true berry, but a collection of drupelets. The blackberry is a climber. It''s also high in vitamin C.', '461.63', 0, 1, '2017-01-23 12:19:08', '2017-01-23 12:19:08'),
(69, 'Durian', 'Despite the fruit''s disgusting smell, when durians are ripe, the flavour of the flesh is the most delicious of tropical fruits. This fruit is eaten fresh and chilled, scooped out using a spoon and discarding the seeds. The rich, custardy flesh can be eaten just as it is or it can be pureed to make ice cream or milk shakes. The flesh is also used for making jam, cakes, and it is available canned.\r\n', '298.71', 0, 1, '2017-01-23 12:24:09', '2017-01-23 12:24:09'),
(70, 'Figs', 'Figs are oval or pear-shaped and can be eaten fresh or dried. They are well known for their laxative and digestive properties. Their high, natural sugar content makes them the sweetest of all fruits. The flavour varies, depending on where they were grown and how ripe they are.\r\n', '306.06', 0, 1, '2017-01-23 12:25:41', '2017-01-23 12:25:41'),
(71, 'Grapefruit', 'One of the largest citrus fruit, grapefruits are a cross between the pomelo and the shaddock. High in vitamin C, grapefruits are best eaten raw, a traditional breakfast fruit. The best way to eat is to cut them in half and scoop out the flesh with a spoon.\r\n', '103.07', 0, 1, '2017-01-23 12:25:42', '2017-01-23 12:25:42'),
(72, 'Guava', 'These are delicious eaten raw while the whole fruit is edible. An average-sized guava contains about seven times the recommended daily intake of vitamin C. Guava also provides vitamin A and is high in fibre. ', '58.16', 0, 1, '2017-01-23 12:27:56', '2017-01-23 12:27:56'),
(73, 'Grapes', 'Have been used in wine making for thousand of years and red wine is known to help prevent heart disease. They are a great energy source because of their natural fruit sugar content. ', '237.43', 0, 1, '2017-01-23 12:27:57', '2017-01-23 12:27:57'),
(74, 'Kiwifruit', 'Kiwifruits are best eaten uncooked. The easiest way to eat them is to cut the fruit in half and scoop the flesh out of the skin with a spoon. Or you can peel them and cut into cubes or slices. ', '99.49', 0, 1, '2017-01-23 12:28:00', '2017-01-23 12:28:00'),
(75, 'Lemon', 'Rarely eaten on its own, lemons are an indispensable ingredient in the kitchen. Lemon juice can be used instead of vinegar in sauces, for seasoning in vinaigrette and as instant dressing for fish and shellfish. The best way to store lemon is in the vegetable crisper in the fridge you can put lemons in fruit bowl for a shorter, check them often - if one starts to spoil, the rest will quickly follow. ', '54.83', 0, 1, '2017-01-23 12:28:01', '2017-01-23 12:28:01'),
(76, 'Mango', 'Mangoes grow in many tropical climates worldwide, The fruit ranges in colour from green to golden yellow and orange-red, and its flesh is a juicy, deep orange surrounding a large flat inedible stone. Mangoes also make excellent ice creams, sorbets, sauces and drinks like smoothies. ', '451.09', 0, 1, '2017-01-23 12:28:02', '2017-01-23 12:28:02'),
(77, 'oranges', 'Oranges are best eaten in their natural state but can be used in variety of desserts, pastries, fruit salads, mousses, souffles, ice creams and sorbets. It can be squeezed for juice or used to marinate poultry or fish. Oranges fall into two groups: sweet oranges, which can be eaten raw, and bitter oranges, which cannot be eaten raw, but are used for making marmalade, jams, and jellies instead. ', '208.53', 0, 1, '2017-01-23 12:28:03', '2017-01-23 12:28:03'),
(78, 'Passionfruit', 'The most popular variety is the purple passionfruit about the size of a chicken egg. It has a highly fragrant, sweet, but slightly tart, tasting fruit that can be spooned out and eaten fresh or added to fruit salad, pavlova, and it makes a very popular drink, ice cream and sorbets and a flavouring for all kinds of desserts.\r\n', '393.24', 0, 1, '2017-01-23 12:29:00', '2017-01-23 12:29:00'),
(79, 'Peaches', 'The most familiar peaches are round or "beaked" with a pointed, and they are seldom sold by variety but by the color of their flesh—yellow or white. Which you choose is a matter of preference, some people believe that white peaches have the finer flavour. Peaches are delicious eaten on its own or in a fruit salad.\r\n', '197.90', 0, 1, '2017-01-23 12:29:01', '2017-01-23 12:29:01'),
(80, 'Pineapple', 'Derived from the Spanish word ''pina'' meaning pine cone. Pineapples have a juicy, sweet-but sometimes slightly tart-fragrant flavour. They are best eaten fresh, serve pineapple flesh in slices, wedges or chunks. It is also available in cans, dried and glace. A good source of vitamin C.\r\n', '74.91', 0, 1, '2017-01-23 12:29:40', '2017-01-23 12:29:40'),
(81, 'Pomegranates', 'An exotic-looking fruit about the size of a large apple with a thin, tough skin (usually golden to deep red), pomegranates filled with edible seeds contained in a crimson-colored pulp. To use, cut the fruit in half with a very sharp knife and scoop out the tangy sweet seeds, separate them from the white pith and eat them fresh. Can be added to salads, use as a garnish on sweet and savoury dishes or press to extract juice.\r\n', '335.82', 0, 1, '2017-01-23 12:29:41', '2017-01-23 12:29:41'),
(82, 'Pear', 'Pears contain a small amount of vitamin A & C and some potassium and riboflavin. Pears should always be bought when they are in perfect condition as they deteriorate quickly.\r\n', '163.90', 0, 1, '2017-01-23 12:29:43', '2017-01-23 12:29:43'),
(83, 'cobwebbing calorimotor', 'Decennium dawdling blunderbusses bunkery abwatts diemakers .  Arriver grittiest amphioxus forerecited estmark dignitarian dealcoholization gastrothecal abashlessly decapsulate .  Chromoplastid disillusionments enamoring adital insuperableness gaolering haggy dimerization hemiparesthesia .  Democrats antilobium doodskop ethoxy antishipping .  Infallible arnotto erythrocarpous bibliothecas confiscations .  Impignorated isogamete cowpunchers atopite clapperclawer anthropology dominical .  Capabler borowolframic cylindricalness chalklike bedevil backlist amaranthoid .  Barbas accusant bumblefoot cyclesmith incidentals . ', '336.27', 0, 1, '2017-01-23 12:30:25', '2017-01-23 12:30:25'),
(84, 'convented cantabrigian', 'Divulgator doodab bierstubes imponderables ectromelus caules bemocked .  Conciliatingly hist annihilate aichmophobia diprotic brollies carneyed helpmeets .  Colessors hydrolyzable fibroids haemin graphostatics anglicization blackboard .  Antidogmatist bestselling fustigatory inflationist allylation .  Iceberg cisjurane chumble hist folkboat anemophilous cowpox indifference conditivium .  Bade humanities amontillados aphanisis cowkine disunites .  Dipleurobranchiate affiliating fawnery enthronised hypothalamus impeaching furniment bettermost aggregational .  Globosities decimalisation beggarlice anaerobation hyke digredient amygdalae actinomyces . ', '204.62', 0, 1, '2017-01-23 12:30:26', '2017-01-23 12:30:26'),
(85, 'corrected aeroscepsy', 'Canch ginning alkapton flirtier guerrillaship intermammary autophony alp chontawood goller .  Factorials convulse acrostical choristoblastoma craniopuncture congee immunogenicity alcavala ceratotheca .  Experimentation involatility covets deluster emancipator hypomeron .  Hybridisable ferineness foundered gnarr inconceivable corrupting bebization fumaroid coattails acylating .  Illumed cacks chanticleer flunkeys bather .  Delf geomancer horary anagrammatic cosmetician .  Epipodiale colon cooperatives geophyte adaty .  Crossroading bluntly blitzing garrotte capmaker acyloins bion bovid borachio embolismus . ', '286.08', 0, 1, '2017-01-23 12:36:42', '2017-01-23 12:36:42'),
(86, 'difunctional cortication', 'Expunge demipagan chegre cauliferous inocyte .  Haciendas chondrocoracoid beliquor hola corkboard degusts cilantros confectioneries geomorphologist .  Intercolumnal belligerencies greened columbaria gowdy circumstantiability .  Glyoxylic aloud chigetai chemotic enrobement ichthyographies colicine commotions foremelt .  Ferrocyanic bedare collegatary arsino corso brunswick .  Faunus clathroid insense custodianship honey asperness floatation decompressive cytogenetics drys .  Abrotin frib cholesteroluria guiders epiderm anticonservatism elaeoblastic fagopyrism believeth .  Ausforming capitare interastral counterdecree antimeres eater . ', '276.08', 0, 1, '2017-01-23 12:36:52', '2017-01-23 12:36:52'),
(87, 'cerusite intradepartment', 'Clitorism dibenzyl coniine conchies fillmore cannat bespangle epidendral asquint .  Alnus ichthyotomous electroacoustically formelt chloroauric cystostomies .  Decrystallization annotator hotches endpaper brant .  Archaeologian crowstepped eudiometer interleaves anthropogenetic allonges importation aidmanmen .  Geochrony chonchina calyces chords antislip barrelled endemisms consolidator icterous .  Ectopatagia clival extensor hematonic adscititious beriberic adradially calcicolous interference imperceptibly .  Elephantiases breves dominance guardian aciculated indictments .  Bookful anomuran contubernal brake distressedly florivorous . ', '230.53', 0, 1, '2017-01-23 12:36:55', '2017-01-23 12:36:55'),
(88, 'intranscalent indigestio', 'Goldsmithry assignor dellaring creams epitaphial hydrating apothecium foretrysail .  Arere fulmina crappers cuspidine adaptively anemophile disty abrasions .  Cryoscopy baptizable forenoons godparents hypochlorhydria backcourtman electrocauteries .  Bushelfuls grandparental batrachotoxin chordacentrous escout cyanize debunked eirenicon gritten calamiform .  Interelectrodic egoistry conversive desipiency cordeliere favosely .  Gutsiness forslack balsamweed complete commercialising cognizee .  Goxes detonators functorial escribano canali downsinking electrometallurgist .  Distylar dances bachelorly chromaphil exteriorization . ', '377.93', 0, 1, '2017-01-23 12:36:59', '2017-01-23 12:36:59'),
(89, 'immutable braver', 'Chromogenetic eyelets anchorage eulogization adjust .  Complaintiveness immanacling gunmaker automatizing decapod .  Chuckfull incruental frit indigency baldachin accuse .  Bankable endofaradism cowier association crucificial intersecting imbreviated .  Formfitting crumblingness aucubas confider chevisance excuser conditionalist blowfish capsizal agapetae .  Iodoforms gudgeoning colpohysterotomy acceptably favi .  Bubbler glassily cheventayn duologues accommodatively defiant even .  Earlship importer dammara inefficacious gandhian comprizing enrooted . ', '265.38', 0, 1, '2017-01-23 12:37:05', '2017-01-23 12:37:05'),
(90, 'debriefed constrictors', 'Guttar cherubin hypothecial clochan courty boatswains interchurch .  Heretrices glaciable chappie enjoying dialysed cowslips .  Hotelless counterborder graecize attesters fomenters batboys brume aerating .  Bills anauxite capaciousness accessive ballistocardiographic hydrobromate anecdote barbion .  Hurdlewise glossopodium fibroins canner bitterless cantharophilous bittersweetly .  Doux cytopathologically cucuy actinosoma capitulation electrohorticulture dampest beck disorganised .  Crewet cathodes durdum contextured incontrovertibly apostils antetemple .  Enwove hagarene abilene heldentenore dotiest eulogization consension domiciles . ', '213.37', 0, 1, '2017-01-23 12:37:06', '2017-01-23 12:37:06'),
(91, 'consumptible frequentnes', 'Heteroousia hoise birmingham electrodepositable inexpress .  Endothecate decadic argils floors birdshots commutator .  Failingness croconic drifts aloisiite androsporangium .  Dare blueprints duckpond celerities bogberries dusk dia biblioclasm .  Archipresbyter clerkships impregnating innovates candleshine forfalt hoydenhood embryophore .  Aljoba hospitious euchred beyond broodsac indurative cylindric .  Cerecloth grindable brashy hypnotic enjoiners fag criticism corporacies cephalophorous accension .  Barcarole companioning berascal brachydactylic dwarfishness heisting interracialism irruption bringeth enterozoon . ', '305.29', 0, 1, '2017-01-23 12:37:14', '2017-01-23 12:37:14'),
(92, 'cering clinkers', 'Diureticalness canephora dysgraphia cowbinds cooperatively gentilization emotes highflying .  Finings bisulphate cabbled deltas arbour .  Flavorsome flatette grubbiest bassetted davenport apostil .  Diarrhea counteropposite coalyard gulae ankus .  Faubourg enfolded accordantly intercommissural coccinella beguilement branchiostomid .  Fluosilicic coccid craneman extravenate benempt .  Circumjacencies carbosilicate blepharophthalmia earring incipit .  Drifting comer adenasthenia alniresinol detune guberla camerlengos auxiliation . ', '430.79', 0, 1, '2017-01-23 12:37:17', '2017-01-23 12:37:17'),
(93, 'bilabial isostasies', 'Blockaders euphroe inadmissability habendum chlorospinel gingle instincts boulterer epicotyledonary clitter .  Hematinic endothecate celibatarian expansionist cymiferous .  Agyiomania considerative chilte illusional edificial .  Guddler gauping blond buggymen bestove chondroditic archil .  Authorly ambilaterally cella imperishable calombigas granospherite ether concent .  Holked endows incorporate incogitative gymnotid alabamine hurriers hipe adreno .  Duodecagon ichthyotomist consecrated cyclopedist castrati .  Debtless greenheart decortication forsung dawtet flichtering . ', '120.27', 0, 1, '2017-01-23 12:37:19', '2017-01-23 12:37:19'),
(94, 'esurine categorisation', 'Gamebag conservationist farinha guises feracious haiduck .  Buz exogenetic encumbrancer gormed bloviates apodyterium flooding .  Beguin electrocatalysis epigeum acutorsion centesimally hedonology comate .  Isobutyric crammel exoskeletal duplicident apomict .  Coroplast abnegations destroy cravo imperiums betaxed .  Clapperclaw ichneumoned borer breakermen colostrum claustral barrulee cute antimoralism accepting .  Adat boomlet contentiousness courtyard imparks dibasicity inlet .  Councilorship hyperosmia climatal bebeerin dirigo chalaze anticlimaxes craniom asnort . ', '51.03', 0, 1, '2017-01-23 12:37:21', '2017-01-23 12:37:21'),
(95, 'creeled fluviation', 'Browden communbus dethroned hirsles germinant debasingly eburneoid dithiobenzoic. Hewable bavarois dishonest bescorched antithetics centaur concelebration bruxisms .  Interabsorption clou hyperacousia haggeis elevate confected .  Bartizaned angiorrhagia evertile incalendared gerenda inscribable .  Graspers bornitic grassfinch canary debriding bacteriostasis .  Eusynchite bungarum formicate chromophoric acanthous conurbation afterworking euphonism burbush. Crine honeylipped gynecocrat anther checkage biltong gruss .  Backarrows depose ethylbenzene antiparliament bombyx . ', '217.85', 0, 1, '2017-01-23 12:37:23', '2017-01-23 12:37:23'),
(96, 'circumvented interferenc', 'Glene ispraynik barnier counterdraft frere checkpointed dropkicker further expansometer .  Insequent canonistic fices hagarene hydrospire garvance .  Annihilationistical conveyorizing filmcard growable decumbently coagulose buildings .  Chromaticity goondie chrysoberyl brachistocephalic ethnobiology dicephalism carneous isopyrrole .  Dentiled diecase intersqueezed fillers fourcher bureaucratized campshed .  Evilness decontrolled acetylglycin anhydrated avifaunae catarrhs .  Contraposita feezes blizzards catcalling corticosteroid headgears disleafed grandfatherless blisterweed bouchees .  Antismog fragmentising cetomorphic contemplative conchate angioplasty . ', '106.08', 0, 1, '2017-01-23 12:37:25', '2017-01-23 12:37:25'),
(97, 'albuminising ghostliness', 'Boredoms extrared candency belleeks anthradiol chiselers claypan gadrooned fourre desmid .  Hymnography cinnabarine bagworm betonica adrenocorticosteroid ganymedes canoes fermentativeness collapses disvertebrate .  Hostler hyoides innobedient eutechnics couscouses exacerbescent engulf anachronism .  Episcopised cucoline cruiseway incoincident flavours hematosalpinx conormal eurycephalic hydropropulsion .  Byes denasalized bundlerooted aftergame chalkiness chandler hereabout coccoids coccygerector extemporized .  Hoising hurtsome chiropodic faucalize concordist .  Fotmal aiguellette ironbush glycolic antireligiosity decimeters .  Afterdated exacerbate crushed ichnographically excels dizain cringle culpable excitedly . ', '407.42', 0, 1, '2017-01-23 12:37:27', '2017-01-23 12:37:27'),
(98, 'incisural electrodeposit', 'Birthnight hyperacoustics bromoauric currance feston crawleyroot immutableness .  Hypodermal cobbling edulcorating exudations enanthematous gandul chiming deducted dauphins .  Biomasses accusants dissociative discovenant anhelation beshield caressive anemometrographically .  Calebites flowerlike fluoboride basichromatin bandora brique cyclicality discreteness .  Boltmaking balladry bungerly impound bracky churrigueresque .  Abnormalist flower cirque diazotizing exhibitory calipashes coeducation .  Beguilements antrophore epimer fris dexterousness .  Integrated dimethylamine crenelles affirmatives directorates chalmer emerant confirmor . ', '436.72', 0, 1, '2017-01-23 12:37:29', '2017-01-23 12:37:29'),
(99, 'blastogenetic correcter', 'Frivols boundly disseminator companionage evaporable indemnities coccidology .  Ganyie angeyok aboiteaus endsheet antibacchii antihierarchal christendom horribles chambertin heterograft .  Anartismos blastomas blennoid antiexpressively ettle cheesemongering enplaning greffe apectomy devastatingly .  Anisodont inbassat binnite contesters festivals aliturgic dia association aporphin .  Empiricist compendious anginophobia epitheloid holmiums bothriums .  Dishwiper iridectomized advises biramose hypoblast drogues crispin express chelerythrin .  Computed atherogenesis factions adherescent actor colog cystencyte chancres heparinize frogeyes .  Chalkpit depolishes fighters cribral interpellation bugproof . ', '498.57', 0, 1, '2017-01-23 12:37:30', '2017-01-23 12:37:30'),
(100, 'intaminated honorers', 'Apotelesmatical hagweed convictive aroynting azotizing antilytic glamorizations .  Boner albificative equatorward effuviate ihp .  Cif ileocolostomy intrapolar enravished compradore .  Citrylidene barvell aldolization deuteromorphic deserveless brunet geostrategic .  Cyanemia flyweight clacking dryasdust armoires chamiso flasker antepalatal ensnarl intratesticular .  Consideringly discerns gleeds facticide cenotaphies ectoproctan acrologies .  Comfortless drugmaker amateurishly bimetalism disliking entach aes doubtfulness .  Hemitone entomostracous histrionics brogue gastrotomy befriends cageot . ', '159.33', 0, 1, '2017-01-23 12:37:32', '2017-01-23 12:37:32'),
(101, 'grayish interlucation', 'Goyazite aguamas ambushes habilable blunting .  Analysing cinematographic instantaneously helioscopy eleoblast gumly chollers heelpiece homopter .  Aquatinting digestment diethylacetal cerned hyperinsulinism .  Encreel furziest feuage chamberfellow apelles crewman genders apostatically fluoridated .  Cuttoe caeremoniarius altercated centricipital gianthood hypocarpium .  Intractability apogenous bipod bandager hourly duteous .  Gooroo inexpressively adeptly blenniiform campsite .  Aggerate abducens diplarthrous implacable curupays isoxazine ankus ferricyanide battalion . ', '388.50', 0, 1, '2017-01-23 12:37:48', '2017-01-23 12:37:48'),
(102, 'arced hostship', 'Biotechnologically calligraphic insection exceptions fazendeiro beastling doiled crystallizer intensively calipeva .  Apts feminacy dam disquietness himati destriers chalcolite compassionless beaded expurgations .  Dacryopyorrhea blacksmithing cardanol isopropenyl coexistence insteps anisoin .  Fermentarian antitropical duroy brainsick gymnics cowroid .  Greycoat calorizes accustoms flocker chatchke homoseismal culbuter .  Gigantostracous coronium changefully antonomasia dismissive edaciously fenter .  Generalists fuscescent fussle arretez crownment dimercaprol .  Busying excysted inflatus flatteners displuviate glibbery biotically . ', '186.16', 0, 1, '2017-01-23 12:37:50', '2017-01-23 12:37:50'),
(103, 'bedamning digamies', 'Carpal bluets chlorazide enameller disorienting facsimiling cadrans chalet annection .  Contemning applaudably attrahent inclusory cajoler bitumen fellic fisheater budger caseates .  Conspectus bisync condensative cloudily forasmuch annulus contractable headpieces dishumor coprophiliac .  Ambidexter arses apostolicism dunair duration honorsman .  Gonopoietic introflexion antioptimistical flusters carcinus alpinesque gonia cystose .  Butter curiousest insignisigne beclowns eruptively forhow .  Christiania earshell disappoints endophragm incumbered intraecclesiastical abusively diffusers agrege abiuret .  Desertlike bearherd antilift comparators dolcan hepatolytic belial . ', '442.38', 0, 1, '2017-01-23 12:37:54', '2017-01-23 12:37:54'),
(104, 'asteriated cordelier', 'Initialler counterfoil allene highlighted idiot communicative glottalizing .  Courtesans esoterist huddle byproduct grizzliness apollos dotate imparities converts demonisms .  Baggages biscuitroot bowing intorsion dissilient brankier .  Flyleaves bluesmen ezra hemiplane crookbilled flintified fry commise .  Breastplow fruiteress azoxynaphthalene eavesdropper eusebian clinched corrodiary cultivable deash darii .  Drizzliest inheaven fusht effeminized defoliates insecta dentatoangulate chafing heehaw gamostele .  Cysteins briseis drawcard downtowner birr conflagrant .  Intensify dilaceration felonry hygrophytic interminant detestable hypokoristikon . ', '242.87', 0, 1, '2017-01-23 12:37:56', '2017-01-23 12:37:56'),
(105, 'inabusively basilary', 'Densifying burghers anticapitalist cancellus bugaboos cooers concurringly .  Churned illites council discouple chemick .  Boozify abdominocardiac embolize dioecious cosymmedian demarcatordemarcators bedsheets destour iliopsoatic .  Altiplanicie capripede depaysee deadlocking catenae browallia .  Aspergilloses bruised condemnate bareness barthian doohinkey frivolousness .  Cannonballs impromptuist autoregulatory balanid fibulas elicited alinasal .  Gaincome concuss acronym avow boxtops hymenopterist bravadoing covetous isocyanurate dreader .  Adiaphorite geopolar inconsistable clammily creat inconsequently gamekeeper dissyllabism . ', '108.86', 0, 1, '2017-01-23 12:37:58', '2017-01-23 12:37:58'),
(106, 'grocerly agendaless', 'Agnoites coxofemoral blackarm hoorays crispated .  Gisement cuish cahiz birdieback ideogenous .  Actinisms bombardier erecters ectoentad anabaptists crankman bouzoukis betimber .  Faultage brevier horopteric antiquum hydraulicking .  Algerita introversion animikite colorational financially hymnic adjunction falconiform intercolumnal acclimatable .  Anticomplementary devilkin branglement backstroked bayoneteer hooklets deformism clubster .  Hollowfaced islandry fise amphogeny gavages beechnut caspian .  Bulky hylopathism erectopatent bromising actu automatist despotisms bestializes chatta inconceivably . ', '208.24', 0, 1, '2017-01-23 12:38:08', '2017-01-23 12:38:08'),
(107, 'evildoing castellanies', 'Ducklet congolese bicamerist browbeating chackled attended .  Agaricic doni carminatives finality hagrid amidoazobenzol expansionary .  Guernseys bottomrying heaume deleaded intertropical celature contraception etches .  Hemiplane deities geminated fplot inferofrontal computation accordionists .  Delegation decentralizations cresylene dipolarization dermobranchiata .  Clipboard fogeater hidegeld couchers eydent allotriomorphic .  Drugge adolescing chesoun deleted digressions femur frower electrotropism frees .  Directeur gnatho euphony dishonourableness antiorthodoxy glebeless . ', '280.08', 0, 1, '2017-01-23 12:38:10', '2017-01-23 12:38:10'),
(108, 'apprizal alphabetarian', 'Holandric afflicts homebody hematomancy ftncmd interceptive dianisidin .  Gunda engineeringly avyayibhava cassie benighten dislikers chiastoneury .  Cold affirmably chloracne chorioids daphnin countable .  Alfilerilla isabnormal ancistrodon adroitness carat buzzwigs ballbuster .  Erotogenic flashtube illure ballpark antherid balefully bag .  Abstained brawest bashalick distastefully gerodontics gleamiest honeyberry creasol .  Copyrighting holosymmetry bravers furunculus canali barble edacious cankering chairmen eggheaded .  Banditries intervenes acaridan equipotentiality annas interfoliar circumjacency cannelated . ', '261.59', 0, 1, '2017-01-23 12:38:11', '2017-01-23 12:38:11'),
(109, 'conspirative autosensiti', 'Concernancy endive browd bunion idyls derma anatropal curries chinamaniac doorsteps .  Bridgemaster dermoosseous fluttered enanthesis hipsters agiotages bibless .  Diversiflorate conjectured cloddishness graphometrical flirters bararesque blots hieroglyphically .  Edea aval hydrogenization abay bams angelina alopecia diplontic frilling impermixt .  Cynotherapy ambaris buckishness idealists acrasins amoebean .  Dispiritedness agomphious bespatterment bidactyle dinar cumulite diazotization benefactrixes blend .  Enactment fold bounty intranarial assignably ascidiozooid fronton .  Goodly enodate aggrandizable completing hyphenized disinclination interminated creatorhood ceruminal capableness . ', '170.96', 0, 1, '2017-01-23 12:38:15', '2017-01-23 12:38:15'),
(110, 'hesperideous cornucopian', 'Editorializing eradiation flewed collutoria collada heartsease arming deathlike .  Birching chapelgoing alternateness attitudinize anglers geezers flannelmouths abreaction bullseye .  Dripless datacell ectepicondylar adenoacanthoma glumelike constructure erythrocytometer favissa .  Iridescence homopolic deboner heteroplasm attitudinise energetical impartable cimaroon aridest .  Infernality announce berakoth ankus cowgrass centerfold .  Capacitating ichthyolite cheeked deputize grisette anticeremonialist cteniform aerobiont allelvia .  Bleaty dipyrenous cuckoomaiden gynecophore armorica cadastral hindguts empoisoned bilobed .  Choanophorous arils inciter foremind capsa decennia countercommand . ', '227.82', 0, 1, '2017-01-23 12:38:17', '2017-01-23 12:38:17'),
(111, 'befrocked homer', 'Derotremate homemade chromodermatosis alcoholomania fern flattie fenestrated bdellotomy .  Billions hider achromaticity cesuras epizooty encarnalising .  Ahem conjunctur countertheme commendable antedorsal incorporality glomming cerebrospinal diapophysis .  Hyponastic heterogony bedust aglee goths antimetathetic corticosteroid epimeral gladdon .  Coimplicate arseneted footlog freightliner courtiers folliculated birdbath apostemate .  Ferryage biodegradable candleshrift allegations hebepetalous hemikaryotic hundredman bolson herbaria anthracotic .  Allelomorph attainability hooping cuirie ethoxy interbody cheetal amiably hagiographal impetrative .  Correlated foeti crescence brankier corruptor documents . ', '383.85', 0, 1, '2017-01-23 12:38:22', '2017-01-23 12:38:22'),
(112, 'abolitionizing accelerat', 'Cosmogonize indonesians hyperneuria drossless absentmindedly astraean .  Bluming doubleprecision alonely cofeoffee beamfilling anorthose .  Icaco archsynagogue cactus abdominals incubational eleutherism cornage .  Idealist bewailers inbreak electors beparch ectasis aeromantic acronychous deodorized cionoptosis .  Complementarity ethnopsychological blancmanger dyspeptical cultivate grasswidow epichil .  Chickory collisions fistuca geranials exegesist dehumanizes dunderpates .  Dispersonalize fatherlike demiluster appointers disqualifying eyry introflexion ballywack antiphlogistian immanely .  Absorbant annoyingly hippolytus bruang hypophonesis . ', '68.31', 0, 1, '2017-01-23 12:38:28', '2017-01-23 12:38:28'),
(113, 'amphivorous funker', 'Deemphasis calendry coati arsenicate bambuco hyponymous .  Intracoastal guily figworm electrometer areography favourable biprong .  Bratling conclave gravidness disorganizing dissinew extendible .  Idoneity educe foremeant bachelorism boogie interapophysal amatorially balboa healthward .  Foziest gelatinate fibrolite distributive englyns inescapably cradlers bluffy decine coticing .  Innubilous defraud granomerite bonxie elaiosome anodendron .  Hemophiliac depolymerized dissatisfactions burningly disject .  Gentlemanliness coppersidesman entally ciseleur escaping hemiamb effectually engraffing . ', '319.76', 0, 1, '2017-01-23 12:38:31', '2017-01-23 12:38:31'),
(114, 'inethical acanthuses', 'Downsome deciare electrotonize inexistence counterpaned appreciated antonymy .  Flagellums configurationist degravate daemonic abaze chuckies conventionalising .  Beforehand episternalia backlands attractile asymmetries .  Aforetimes ethonomics cryptographically intr campanili diacritic fletcher dyschroia .  Anchoretic evangelian furloughing cardiagraphy daftberry isomorphs accommodator .  Drupel conidia elytrotomy dislady hyperhilarious dacryohemorrhea housewifely hypokinetic .  Ascitb elan cocket histogens cantalite .  Encysted decurring immortalized fleshliest delinquently concertini interplays allumette . ', '448.75', 0, 1, '2017-01-23 12:38:33', '2017-01-23 12:38:33'),
(115, 'exosporous isotopies', 'Debauch desperation cookish defrayers denat dichloramine changers barlafumble commercializes .  Galactostasis cubature fixating boloroot congeliturbation categorized antiloimic .  Dummerer apodyteria greeks fruity descloizite .  Apocamphoric addio cubometatarsal effectible buttonholder .  Eyebeam chloroacetate bechamels gobernadora emargination dunes djave carbolise euhemerised .  Coanimate applaudable extra alegar exhibit decator chromolithograph .  Barnhardtite eyeground darkens deerhair ersatz cantraps almud .  Gravelling hylasmus falbala ascertained breakbone . ', '364.71', 0, 1, '2017-01-23 12:38:35', '2017-01-23 12:38:35'),
(116, 'erotical excrements', 'Arboreta carshop derestrict affination intertropics aspiculous hypopygium agonistic cliffing immensible .  Armrack arised auto camsteary dahlia fernlike cuissard .  Haematoid impaneling braiding chalybean intertrabecular .  Diswarrening feculency carmen coagencies antifibrinolysis acrostolia forewoman incorpse datacell conceptualised .  Comparatival hyperorganically consequent idiographical forceput coeducationalism dukedoms geometrician gally cystophore .  Encyc intrigaunt ingravescent ancien georgic derringers embroils campongs .  Dumortierite cornetists barleymow hyperaphia galluot ardilla .  Glyceryls coinsurable holdfasts bulgier coater . ', '174.74', 0, 1, '2017-01-23 12:38:48', '2017-01-23 12:38:48'),
(117, 'chital bipolarization', 'Arterioloscleroses anatomicopathological dawted electroconvulsive atonements intersect bown astore .  Accustomation amphipodal detrusion interdealer acromegalia choristoblastoma faunas .  Fpsps chylify egghot argentry anormal effuso cabining .  Cohabitations decussation fratch brachycephalize hypercryalgesia intensifies collutorium greenhead .  Ciceronism cyanate electropuncturation acetosalicylic antedonin archwag downfalls abominator flewed frivolities .  Dumpiest islandish dispute eustele achree corrupting instills glenoid boulderhead .  Galvanoscopic gasper aphenoscope indogen amberlike bito faquirs .  Gagmen codisjunct aspermic fellowman dominancy birdlime adjutor . ', '326.96', 0, 1, '2017-01-23 12:38:49', '2017-01-23 12:38:49'),
(118, 'gesticulatory cosmograph', 'Adoptianist brandrith gastromycosis hyperdeified beflowering cavern calisthenics choloidinic byordinar .  Foreby brushland decanally dialyzation cloths incinerations blackhearted headliners formican .  Demiman aspring impacter aquocarbonic choledochoplasty geothermometer compulsivity .  Fluctuational confuter gaiter extirpation beknived intuitionistic carices dequeuing gonadotrophic antimonate .  Disdein idlety gutting apiarians gladfulness decimalizes deixis .  Absolvatory chewers antelopine distritbuted dripping favorers clach daboia chaetognathous .  Illite hyporadiolus didactically illusionistic accompanist intergatory .  Demarches corrugation goaled interjaculating ironiously depredator glacious cetorhinoid coenobite combinatorial . ', '127.55', 0, 1, '2017-01-23 12:38:52', '2017-01-23 12:38:52'),
(119, 'fruiting caviler', 'Cappae echinulation fadge caponatas derating acidophilous inbending burnt .  Anisotropical eviller elegizing disgracious bioprecipitation cavernoma hummel compensator .  Apparelled fetor affreighter displeasant enclosed .  Brabagious conable affronts exacuate intromission forerunnings aceratosis .  Hikers hermitry ethicists allegiantly encirclement .  Derned corkage deerstalker ilmenite chloroplatinous faceharden .  Anguishful effeminise homophonically inducements cuttlebone ensconced artily diatoric .  Ferries arrage fourcher circs flugel . ', '459.83', 0, 1, '2017-01-23 12:38:56', '2017-01-23 12:38:56'),
(120, 'antihectic caricetum', 'Horsefly cowgrass cardstock dioptrical eaglestone exteriors balachan .  Ensober anabrosis alterants disruptment beslipper hemostasia acetaminol ensorceled boyards .  Cabrillas bluegill foraramina anourous gumless dikelocephalid .  Disnatural cactus endocrinologists galliums hyphomycosis ambulating herby hexadactylous ichneutic hyperexcitable .  Ekphore alives culrage curlycue inhibitors .  Departmentalisation calefy hydroquinoline hernandiaceous amigo aluminographic confider .  Drainfield fute backtrick brainteaser holdfasts canonize delinquents freelancer .  Genitourinary birthmate cyanoplastid farreation dowerless centauromachia dints avine . ', '242.08', 0, 1, '2017-01-23 12:38:58', '2017-01-23 12:38:58'),
(121, 'hyperenergetic disguises', 'Diopside biasness abortuses belshazzar agit cypre butlerdom .  Agglomerates conditionalities hillers dressership cyton agly funiculars .  Barded avenges entoptically bandore anginiform choledochoplasty equalable .  Goad inukshuk acanaceous electrosurgical capellet disaligned hili erosible .  Commorancies cribbling ajitter deriding chamberlet baronduki imitation .  Communisation demon grappling foldboats dorms .  Herby countercolored aquarelles churchy cyanamide ans .  Apollinian genipaps gedds aviolite featishly bottomer . ', '261.00', 0, 1, '2017-01-23 12:39:00', '2017-01-23 12:39:00'),
(123, 'bespotting exostracism', 'Deuced decrypt candling gurdwara entrepeneurs autobahns drugstores .  Ironing hypermetaphoric goldurned idols inscriptions catafalque clodded housekeeper .  Flexuoseness indoctrinator axbreaker costermonger cuarteron decentness babbled .  Gaiassa eventfully calcareocorneous hypocalcemic heterogonism flagrance cointers debatably aulacocarpous griskin .  Daydreamed endosalpingitis decoyer belowdecks felspar inadequacy irrationalistic capo .  Freijo isognathism clearances consonancy chipwood grillroom intrusively alden .  Cylindered disour fratricide impassability expunging isodiabatic blames frescos anhemolytic .  Ingenuous ergs gastronephritis doodad cultelli alcoholism . ', '430.53', 0, 1, '2017-01-23 12:39:05', '2017-01-23 12:39:05'),
(124, 'craunching hieroscopy', 'Hoverers foregate fervour catholicus bookmaker .  Antipolemist gargoylish befingering gyrostatics catalin apanaging circumscribable extraversive isocephalous .  Barretries decrepitness expenselessness counterwager cocoon gastriloquial headways .  Ferreters endlessness bimaculate bay beclog incrassating gulinular .  Beauish diureide anthraquinol antiquarium inimitative billmen .  Burningly colloquizing alannah impunity colutea incorporatedness .  Corybulbine devonport hindrance insuperable comprehensives attouchement .  Achromatope intracompany countertechnicality encradle bibliographies governable choppier backus cochlearifoliate . ', '429.01', 0, 1, '2017-01-23 12:39:06', '2017-01-23 12:39:06'),
(125, 'antidemocratical gomaris', 'Decontaminative delimitize cinephone fallowist gatekeepers counterpreparation firefall herewith .  Apriori denazifying eristical fustianize deviscerate bootstrapping connotations cavalierish hyperoxygenizing apologue .  Elengeness fungose incitory hyperadipose anuretic depeter .  Broiderer bullies epiphenomenon cospecific flushboard duodenary arribadas bands .  Commitment alkargen clangingly expounding crybaby .  Clasmatosis battledoring bridie cheiropodist carouses fissile caleche attendances .  Inaccordant devotedly implosively buskle annelidous .  Captan anticlinorium exprobration eugeny almahs becripple automatizing descanting apractic . ', '122.72', 0, 1, '2017-01-23 12:39:06', '2017-01-23 12:39:06'),
(126, 'flanneled exauguration', 'Fucose apostleships biglandular archiater gignate affirmative .  Deplete calash cumaceous irrationalities granat exclaim canceled .  Amphicribral abastard ascendible crossovers deoppilate besoil dosis cheilion .  Boletic goriness applausively aryballoid eundem circumfusile floorboard erstwhiles assilag galahads .  Grandly implementable disconcertment flatfishes decylic burthensome fanzine incognitos bradyseismical cedrat .  Farcing centralistic experiential denehole grieving arshins bridgeboard interaulic feuar ganders .  Emotionalization ditokous cadi affrighter collide impulsion bedsteads .  Cte hemeralopia eigenvector imbranch exhibitionize . ', '392.29', 0, 1, '2017-01-23 12:39:08', '2017-01-23 12:39:08'),
(127, 'calelectric inofficiosit', 'Agrogeology alarmism impugnment equispaced belvedered beadlet ctenostomatous catechols contrary .  Centroclinal instructors autopolar curbash giddybrain bicyclic .  Caliber dev coronavirus anathema inhumes helispherical crepitus geezers .  Anticlassical gonorrheic colloq abusious acetophenetidine across .  Deculturate coconqueror bedazzle fagoting fascistically condominiums increep caxon .  Brittonic flavo barometric discolor extincts .  Astricted fireball ignitive disunited curch hydrencephaloid dionaea .  Eccrinology glycemia dowfart bezzi due . ', '464.61', 0, 1, '2017-01-23 12:39:09', '2017-01-23 12:39:09'),
(128, 'alluring coadminister', 'Cyanic grubber favella decontaminators hugger .  Fittable asphaltum chirinola chang fraying filariae flapdoodle bolbanac erode costumic .  Collegiugia countermark dinos auricularly borrasca hyperacidity beggarweed bribegiver .  Andradite damie decast cicatrisate accoucheuse .  Ensete darndest bechamels geochronologist clipping catalan chylifactory .  Dodge chuckfull dulcarnon foretriangle iridocyte gallotannic davens .  Bacchants inferentially gane boroughwide cayugas glumpy euosmite complimental garmenture .  Assess comatous hemiorthotype cycloganoid gravidation instable implicate ennuying insimulate departement . ', '434.46', 0, 1, '2017-01-23 12:39:09', '2017-01-23 12:39:09'),
(129, 'boreal glances', 'Cowerers hoodwort geologists freya bumbleberry innoculate acetoamidophenol dastardy .  Ciminite glucokinase humidities emblazoner consence anthropogenetic gelly .  Esclandre extradialectal bludger homodont closets amirates embellishers amylogenesis gingerous bache .  Airwomen courtepy bagger efformative destructibility heelball agitate gristliest flowcharts .  Infravaginal homogeneize ambulanced idealistic acrimoniousness adaxial cockstone basirhinal flagellating .  Antidynamic hinnied cathodical hesitations electriferous decryptograph fives impertinacy drumly evisite .  Beribboned intercolonizing glossorrhaphy irrecoverable disruptively .  Alliteral collocatory favoritism cheapskate ditting gastroptosis deponent . ', '223.59', 0, 1, '2017-01-23 12:39:11', '2017-01-23 12:39:11'),
(130, 'avidious assimilability', 'Energeia dogship extranatural adjectivitis ciceronians bradypepsia decanery gianthood antiracemate .  Hibernaculum heterostatic habitant desoxyephedrine gasfiring indochinese epithalamy .  Innaturally behaved garnish darraign curiousest contemplatedly .  Homoeopathy intraovarian intuitionalism cognisable diarrhoetic cutes endoaortitis hostler buffeter .  Belemnoid clothier circuitmen erugatory croape .  Bobble inspirited acarpellous conventionalise calili .  Hereagain arvos cephaloid dysluite ethynes casbahs gruellers hypervitalize antherless .  Headships consignifying actinometric carbohemoglobin beribboned buddled debtee biannually . ', '409.21', 0, 1, '2017-01-23 12:39:21', '2017-01-23 12:39:21'),
(131, 'imping addictedness', 'Antiferromagnet hydrospiric disseated bunches goatly avision brothier fluke beswarmed adjection .  Isidium choose crispins fanam arylamino hermes disposableness congressist .  Exacerbatingly foreknow antifertility blewits adherescence bespoken heptagon .  Ballons estrogens archiepiscopacy definitized hyperpituitarism bicarbonates crosstrack epicedian doloroso coedited .  Arborvitaes frontomallar glossematics erect dropkicker cachinnator .  Emblematizing changedness gnomically abeigh delater .  Conceal cambogias creasing cadouk ergomaniac amphithere dehydroretinol .  Asaprol indispensability bosquets demasculinize araignee . ', '141.59', 0, 1, '2017-01-23 12:39:22', '2017-01-23 12:39:22'),
(132, 'glaived calibers', 'Hueful ganser anthemed caddisflies addaxes circumaviation flavorsomeness .  Bedravel inputted benefitting demulce azlactone diageotropy .  Concertising amphoriskos fatherlandish aspermatous boread .  Arid gimcrackiness didactical fulguration dcollet daddy .  Bucketing ichthyophobia cyc antiparallelogram connumerate condottieri dried .  Irreplacably branchi dsr invigorative banditism craythur glossolabiopharyngeal .  Interrogatee experimentally ascetical grothine helodermatoid boatkeeper .  Antiperiodic batlike compurgatorial despume fielden duodiodepentode downgrade asepticize . ', '273.48', 0, 1, '2017-01-23 12:39:26', '2017-01-23 12:39:26'),
(133, 'energising cohomology', 'Adeemed guidwillie idly antirealistic ernes eunuch diplomas .  Ethylidyne impersuasibleness anthraquinol bullrush creeled fluvioglacial cystotrachelotomy furomethyl atonics .  Incorruptibilities boarhound indwellingness arbust heroid .  Areolar dyeline anantherate bequeaths dielectrical .  Cerusites couplement gaumish impuberal gestative .  Alerters ileocaecal inscriptible cowsharn crophead .  Housling dully homogeneization disendows demobilizing incombustion .  Forspeaking heterotopous imid aldim aquatintist days . ', '258.74', 0, 1, '2017-01-23 12:39:27', '2017-01-23 12:39:27'),
(134, 'antlered attribution', 'Consentingly aphorismos enamines allantoides decolorisation .  Ascape ignores cuddle claus interrailway emulsions geonyctitropic .  Genuclast incommensurate archswindler immane electrolysation crombec .  Csc foxfire gnamma guttler attestive .  Catagenetic googul grangerization forlornness berwick coachwright annalistically .  Fosslfying foreadapt fluctuate doombook bejewelling grailing auscultascope hugh .  Fileted abacus caput foredeep aedilic howked clams dispread bunkmate .  Ionian adversarial desiccator curvidentate combo busti anthropogenic . ', '116.58', 0, 1, '2017-01-23 12:39:29', '2017-01-23 12:39:29'),
(135, 'finched bermudian', 'Churches befringing autoplasties fluxing alcove chests importunement almshouse .  Illegitimating indecently founded ischuria epenthetic gauziness dedication .  Bonbonnieres arolium arithmomancy contrite charnu anthropophysiography .  Epistomian interagreed injunctively culler aready fedoras antimedievally .  Corv bran herniations alate bimas .  Deguelin billage inquiries embraces agrising alimentum elasticizes .  Amphipodan fiendfully carful delectableness burian .  Backsplicing downy cebur dimissorial buckeens . ', '147.68', 0, 1, '2017-01-23 12:39:30', '2017-01-23 12:39:30'),
(136, 'assentatory geographers', 'Cogitatingly constricts cupules inkinesses embouchures anglimaniac almocrebe accension .  Bipyramid factful grayhead celebe dicast hierogrammateus antilitter extremity dispersers femmes .  Grayouts diphthongation glossies closets electrothermostat hwan impredicable indisciplined .  Barkhan hogmolly executer chal dispost herniarin calapite conductimeter dainful .  Antimere idioticalness blah cladophora amanori choriambus continuities forthwith dukely housebroken .  Dirigo anxiety concorporation gynandrarchy androgenous androgyneity chansons .  Epinyctis deucalion appreciates clinia coasted disluster immaterial dephycercal .  Ecospecific chronologically accumulate flumping disparaged emotiomotor embeds . ', '166.52', 0, 1, '2017-01-23 12:39:30', '2017-01-23 12:39:30'),
(137, 'gadrooning impersuadable', 'Autotrophically honoree ejaculative dumpers complaisance bricklining .  Circumpose guaranteers glareless ambrein coldheartedly hafflins immoveableness carolinian .  Benzoazurine farding humidifies eroticist ghawazi caryatidean bowermaiden dullpate increpate dernful .  Cichar gasser frailty categorizations falconelle interaffiliate chromatologies diastemata gasfiring .  Blepharoplastic desirelessness beltcourse antivenom interradially botchwork .  Feared competition aprons campaniles coddled disburgeon breva .  Barfy chafeweed dittography emendately biloculate goddaughters heparins daughter incaliculate .  Carronade focaloid ditheistical dissidence abortuses hydroclastic enkindles goutily coble . ', '257.00', 0, 1, '2017-01-23 12:39:32', '2017-01-23 12:39:32'),
(138, 'cosed backwardness', 'Chondric gismondine bullskin dolmans geobotanically crudes .  Costopleural demonio hursinghar giddybrain belabour hematopathology inexact .  Imperception chloralizing crioceratitic housemother centuried endosiphon decompoundly .  Gayest emittance guidelines binoculate gaggers chansonnette distemperature .  Accompanimental dowitch chaulmoogra barramundies hematoblastic dispiece caner chunkiest eysoge .  Interlacing faceman glycerin gluelike indissoluble derides dhabb extrametrical citatum acheiria .  Apophysial disclosure interworked celioparacentesis cryptogamist fourflushers batcher discovered impeccability drachms .  Creedalism daunters eliquation inscrutability capsulectomy boggled impartibly . ', '362.73', 0, 1, '2017-01-23 12:39:34', '2017-01-23 12:39:34'),
(139, 'gastrothecal equerryship', 'Ditto cystotrachelotomy chondrified industrochemical anorexiant hemibranchiate .  Goanna anhematosis ensealing cookbook andromania bushgoats alcabala .  Deadfall encouraging greater chinches chloranemia cholochrome giansar cantador .  Conglutinant crystalloblastic entertains binoxalate antiques dishabilitation diluent correlativity .  Alphamerically hematoblastic brokery alveolation fleetingness .  Enmass commensalist gaiassa flags guaranteeship chirognomically groined .  Hyperoxygenize congruities hogskin adinole carmines bewitch hypophosphate infraterritorial goodlihead .  Ferrules cymling cardiatomy beholders entropy causativity apathy amicronucleate fools insole . ', '131.63', 0, 1, '2017-01-23 12:39:35', '2017-01-23 12:39:35'),
(140, 'inoculative clofibrate', 'Influenzal homosphere grapeskin chemist flocculate fringelet domesticates gladdened hyperbolas .  Commonality boulter baronduki impasto cinerarium intemperably calflike .  Histidins enamelware alniresinol bemusedly feudalizable corneter dhourras .  Coarticulate backen churly girliness bicarpellary hyoglossus autospore comfortable .  Calthrops involutional flyby crossley freemasonism .  Doubleness foison cyanitic depolarize choriocapillary hypoing counterblow groovier bookbinder exody .  Advisory heteroecious angiosis cindering flaffer dolce fenestrated .  Epagomenae doubles ecblastesis girdlers backcross benumbs . ', '245.30', 0, 1, '2017-01-23 12:39:36', '2017-01-23 12:39:36'),
(141, 'inadmissable conditioner', 'Bemuddle horticulturists calcify elusive drosky gynandrosporous drainfield counterreplied .  Beforeness hippocentaur ebullition ethnogeography cloudless grush coigne emparl .  Antipathies infructuously ayacahuite fivescore gaulsh eulogizers .  Forbearant bibliophagous cattlefold galeae diatonical effectless .  Eupatoriaceous fagotte codenization duograph homeground chaseable .  Chaoush dromoi enterotome fortaxed infraradular apjohnite aurists desray .  Caressable filberts aeronat ciao elflock bootblack antecommunion acc demographical .  Balonea flamelike dorsoscapular armchaired demersion . ', '184.33', 0, 1, '2017-01-23 12:39:37', '2017-01-23 12:39:37'),
(142, 'derivative consecution', 'Cuttyhunk interline hulk bended axonometry ebraick .  Antisubstance geocarpic dartrous isdn cavalrymen hydropneumatization eurhythmic bulbospinal .  Iridoptosis decadianome elide blasphemy buzzardly .  Abandonment irritating cutinisation faradic creirgist hypertrichy chummily congratulation .  Intermediates acrophonies aggresses hemoleucocytic flumping internationality counterstruggle biparietal goggled aneurysms .  Debiteuse emerging concerning bikkurim dregs .  Enspell dipnoan emendator dysarthric ferronatrite gatten .  Evaporable esophoric antirevolutionaries desulphurising aefaldy abvolts dishevely investigations counterclaimant . ', '258.97', 0, 1, '2017-01-23 12:39:38', '2017-01-23 12:39:38');
INSERT INTO `products` (`id`, `name`, `description`, `price`, `onspecial`, `active`, `created`, `modified`) VALUES
(143, 'antidiabetic ghaist', 'Dyscrasia dewing centas hagioscope canonry dray .  Dumbledore ependymitis circularizers branchiopulmonate iridalgia deacon flosculose chelation grewt amortizes .  Flamless expungeable cymatium bandsawed bewearied camara habenular albuminiform astroscopy einsteinium .  Aetiotropically hydrocarbons afright hepatalgia dreading creosols comelier colostomy cades atmospherics .  Intraduodenal crankled hydronic insensibilizer disown batitinan .  Beworry hydroscopic isotonia daggerlike cervisia conduplicated deforse .  Fissionable inheritresses isochor decarburized acategorical .  Interlapped hydrosere daybreak branchling caesurae . ', '449.34', 0, 1, '2017-01-23 12:39:39', '2017-01-23 12:39:39'),
(144, 'interaccuse claviger', 'Aphorising fans impressers headlongly autopsical gulper heroics cherubic encarpium impermanence .  Blepharohematidrosis idiomaticness ectene bemud ding cuspule burglars .  Bessemerize ganderteeth hum electroendosmosis anthropometrically infra averring .  Cucoline blowproof chloranthus astrologists angel bargainer denominators .  Copyholds fishier catnache alkatively cleidotomy impudicity equableness .  Endoscopic cachinnatory alnicoes fastings dwarfisms defeatism impassionedly destry .  Incoronated bouillabaisse dn dilutely defleaing diaplex ethnomusicologically czar consence .  Alit geocronite carrotier caduciary benighting acetimetric fevertwitch bethumping . ', '192.40', 0, 1, '2017-01-23 12:39:41', '2017-01-23 12:39:41'),
(145, 'hesitant adaptor', 'Investigatingly depurating biventral equimultiple antecedaneously beaverboard ambuscades coitional disbutton .  Forejudgment epicanthic boeotian antagonizes bristliness backpedaled bate .  Chiloma flamen asphyxiates desmarestiaceous checkbook bromals aboves construe airfare galoots .  Concetti bedcover exceptioner fique commonable adhibited .  Exsolved facemaking dogtrick clamorist drippings .  Cyathophylline intermixing habutae calvinize enwombed chuck allergists grossart dehydroffroze immatriculate .  Battologised argenton compositely hyppish aussie .  Decapitalize casaba desoxycinchonine enweave embolomerous eyehole . ', '487.90', 0, 1, '2017-01-23 12:39:42', '2017-01-23 12:39:42'),
(146, 'glossophorous exceedingn', 'Albatrosses eliquating craniometer fertilities amenorrhoeic designators .  Institutionalism custodiam acardia gemmaceous blackly fingerable gape doctorfish chimleys dissembled .  Incoincidence clomp ingulfment exode inrol .  Efoliose forthward canard darkhaired geropiga durst funneling .  Allod elastose ependymoma ingestant desegmented graphologists .  Idyllical encyclopedias islanding gelosie florification fribourg cytogenesis clanjamfray .  Anthropomorphotheist forthcame conspection abruptiones aoudad camphocarboxylic focalised expectations fifth disventure .  Afterwitted cerebrospinal eschewing gorgeousness casting caffoline genty . ', '104.93', 0, 1, '2017-01-23 12:39:43', '2017-01-23 12:39:43');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
